apiVersion: v1
kind: ConfigMap
metadata:
  name: hosted-config
data:
  SPRING_MAIL_HOST: "smtp.dev-example.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
