apiVersion: v1
kind: ConfigMap
metadata:
  name: hosted-config
data:
  SPRING_MAIL_HOST: "smtp.example.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hosted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hosted
  template:
    metadata:
      labels:
        app: hosted
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "flashcards-hosted"
        vault.hashicorp.com/agent-inject-secret-hosted-config.properties: "kv/data/flashcards/hosted"
        vault.hashicorp.com/agent-inject-template-hosted-config.properties: |
          {{- with secret "kv/data/flashcards/hosted" -}}
          spring.mail.username={{ .Data.data.MAIL_USERNAME }}
          spring.mail.password={{ .Data.data.MAIL_PASSWORD }}
          {{- end }}
    spec:
      serviceAccountName: hosted-sa
      initContainers:
        - name: wait-for-vault
          image: curlimages/curl:8.10.1
          command:
            - sh
            - -c
          args:
            - |
              echo "Czekam na Vault pod http://vault.vault:8200/v1/sys/health..."
              until curl -sf http://vault.vault:8200/v1/sys/health | grep '"sealed":false' >/dev/null; do
                echo "Vault jeszcze niegotowy, śpię 3s..."
                sleep 3
              done
              echo "Vault gotowy."

      containers:
        - name: hosted
          image: flashcards-hosted
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "hosted-service-group"
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: "earliest"
            - name: SPRING_KAFKA_PRODUCER_ACKS
              value: "all"
            - name: SPRING_MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: hosted-config
                  key: SPRING_MAIL_HOST
            - name: SPRING_MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: hosted-config
                  key: SPRING_MAIL_PORT
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              valueFrom:
                configMapKeyRef:
                  name: hosted-config
                  key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: hosted-config
                  key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE

            - name: LOKI_PUSH_URL
              value: "http://loki:3100/loki/api/v1/push"
            - name: SPRING_DOCKER_COMPOSE_ENABLED
              value: "false"
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/vault/secrets/hosted-config.properties"
